I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 85, in script
    return
Exception: Could not find return label (u'C:\\Users\\STEM-Student\\Documents\\GitHub\\mth/game/tutorial_chain.rpy', 1462989759, 9).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 85, in script
    return
  File "C:\Users\STEM-Student\Desktop\renpy-6.99.8.7z\renpy-6.99.8-sdk\renpy\ast.py", line 1367, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "C:\Users\STEM-Student\Desktop\renpy-6.99.8.7z\renpy-6.99.8-sdk\renpy\execution.py", line 503, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'C:\\Users\\STEM-Student\\Documents\\GitHub\\mth/game/tutorial_chain.rpy', 1462989759, 9).

Windows-8-6.2.9200
Ren'Py 6.99.8.959
mth 0.0
